# Generated by Django 5.1.2 on 2024-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_snippets_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highlited',
            field=models.TextField(default=''),
        ),
    ]
